In [1]:
import numpy as np

In [2]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten

C:\Users\MOHIT\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((60000, 28, 28), (10000, 28, 28), (60000,), (10000,))

In [5]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [6]:
x_train= x_train.reshape(60000, 28, 28, 1)
x_test= x_test.reshape(10000, 28, 28, 1)

In [7]:
from keras.utils import to_categorical

y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [8]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((60000, 28, 28, 1), (10000, 28, 28, 1), (60000, 10), (10000, 10))

In [9]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [10]:
batch_size= 100
input_width = 28
input_height = 28
input_channels = 1

n_conv1 = 64
n_conv2 = 32
stride_conv1 = 1
stride_conv2 = 1
conv1_k = 5
conv2_k = 5
max_pool1_k = 2
max_pool2_k = 2

n_hidden = 1024
n_out = 10


In [11]:
model= Sequential()

In [12]:
layer1= Conv2D(filters= n_conv1, kernel_size= conv1_k, padding='SAME',
               activation= 'relu', input_shape= (input_height, input_width, input_channels))
#layer2= MaxPooling2D(padding= 'SAME')
layer3= Conv2D(filters= n_conv2, kernel_size= conv2_k, padding= 'SAME', activation= 'relu')
#layer4= MaxPooling2D(padding= 'SAME')
#layer5= Dense(units= 1024, activation= 'softmax')
layer6= Dense(units= 10, activation='softmax')

model.add(layer1)
#model.add(layer2)
model.add(layer3)
#model.add(layer4)
model.add(Flatten())
#model.add(layer5)
model.add(Dropout(rate= 0.2))
model.add(layer6)

In [13]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [45]:
model.fit(x_train, y_train, epochs=5, batch_size = 100, validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/5
60000/60000 [==============================] - 11s 179us/step - loss: 0.7960 - acc: 0.9114 - val_loss: 0.0669 - val_acc: 0.9794
Epoch 2/5
60000/60000 [==============================] - 10s 163us/step - loss: 0.0658 - acc: 0.9805 - val_loss: 0.0612 - val_acc: 0.9818
Epoch 3/5
60000/60000 [==============================] - 10s 163us/step - loss: 0.0531 - acc: 0.9837 - val_loss: 0.0659 - val_acc: 0.9819
Epoch 4/5
60000/60000 [==============================] - 10s 164us/step - loss: 0.0420 - acc: 0.9865 - val_loss: 0.0693 - val_acc: 0.9815
Epoch 5/5
60000/60000 [==============================] - 10s 163us/step - loss: 0.0357 - acc: 0.9891 - val_loss: 0.0864 - val_acc: 0.9805


In [46]:
predictions = model.predict(x_test)
predictions

array([[2.2316075e-07, 6.2122447e-14, 1.2378038e-06, ..., 9.9998760e-01,
        1.2766610e-08, 4.0952699e-08],
       [1.4904518e-13, 4.4929941e-08, 1.0000000e+00, ..., 1.0041404e-14,
        3.8739710e-12, 5.3715470e-19],
       [1.4711311e-10, 9.9691182e-01, 4.5546798e-07, ..., 1.5758025e-10,
        3.0753713e-03, 9.5948416e-11],
       ...,
       [7.7049759e-15, 2.1492167e-13, 2.1455525e-15, ..., 4.3998288e-11,
        8.6103769e-10, 8.0626064e-14],
       [9.9041847e-13, 2.7725269e-15, 8.9241131e-13, ..., 4.3237796e-14,
        9.2519891e-05, 7.7993097e-13],
       [1.4053786e-04, 1.2147413e-09, 3.0839917e-06, ..., 3.0029587e-10,
        5.0624948e-07, 5.6039720e-08]], dtype=float32)

In [47]:
score = model.evaluate(x_test, y_test)
score

10000/10000 [==============================] - 1s 116us/step


[0.08644150696715878, 0.9805]